# Load this properties before executing the scripts
# source config-properties

#####################
## Main properties ##
#####################
# Set the PYTHONPATH to where this project is located
PYTHONPATH=
# Set these regardless of where your Event Streams on prem or on IBM Cloud or a local Kafka instance
KAFKA_BROKERS=
SCHEMA_REGISTRY_URL=

######################
## OCP and IBMCLOUD ##
######################
# Set these if you are using Event Streams on prem or on IBM Cloud
KAFKA_USER=
KAFKA_PASSWORD=

#########
## OCP ##
#########
# Set the SSL certificate location if you are working against an Event Streams instance on OCP
KAFKA_CERT=